
package ir.iais.sana.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2021-03-27T14:44:15.287+04:30
 * Generated source version: 3.3.5
 */

@WebFault(name = "InternalServerException", targetNamespace = "http://servicebus.sana.ir/PushSana/v4/")
public class InternalServerExceptionException extends Exception {

    private InternalServerException internalServerException;

    public InternalServerExceptionException() {
        super();
    }

    public InternalServerExceptionException(String message) {
        super(message);
    }

    public InternalServerExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public InternalServerExceptionException(String message, InternalServerException internalServerException) {
        super(message);
        this.internalServerException = internalServerException;
    }

    public InternalServerExceptionException(String message, InternalServerException internalServerException, Throwable cause) {
        super(message, cause);
        this.internalServerException = internalServerException;
    }

    public InternalServerException getFaultInfo() {
        return this.internalServerException;
    }
}
