
package ir.iais.sana.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2021-03-27T14:44:15.387+04:30
 * Generated source version: 3.3.5
 */

@WebFault(name = "MisMatchIndexException", targetNamespace = "http://servicebus.sana.ir/PushSana/v4/")
public class MisMatchIndexExceptionException extends Exception {

    private MisMatchIndexException misMatchIndexException;

    public MisMatchIndexExceptionException() {
        super();
    }

    public MisMatchIndexExceptionException(String message) {
        super(message);
    }

    public MisMatchIndexExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public MisMatchIndexExceptionException(String message, MisMatchIndexException misMatchIndexException) {
        super(message);
        this.misMatchIndexException = misMatchIndexException;
    }

    public MisMatchIndexExceptionException(String message, MisMatchIndexException misMatchIndexException, Throwable cause) {
        super(message, cause);
        this.misMatchIndexException = misMatchIndexException;
    }

    public MisMatchIndexException getFaultInfo() {
        return this.misMatchIndexException;
    }
}
