package ir.iais.sana.domain.sanama;

import javax.xml.bind.annotation.XmlAttribute;
import java.io.Serializable;

public class Report implements Serializable {
    @XmlAttribute(name = "AccCode")
    private String accCode;
    @XmlAttribute(name = "SummaryProgressDeptor")
    private long summaryProgressDeptor;
    @XmlAttribute(name = "SummaryProgressCreditor")
    private long summaryProgressCreditor;
    @XmlAttribute(name = "SourceEssence")
    private int sourceEssence;
    @XmlAttribute(name = "OtherSourceType")
    private int otherSourceType;
    @XmlAttribute(name = "CreditType")
    private int creditType;
    @XmlAttribute(name = "TransferalType")
    private int transferalType;
    @XmlAttribute(name = "CreditInfo")
    private int creditInfo;
    @XmlAttribute(name = "ExpenseArticle")
    private int expenseArticle;
    @XmlAttribute(name = "ConstructArticle")
    private int constructArticle;
    @XmlAttribute(name = "ExpenseDetailArticle")
    private String expenseDetailArticle;
    @XmlAttribute(name = "IncomeCode")
    private String incomeCode;
    @XmlAttribute(name = "IncomeSubject")
    private int incomeSubject;
    @XmlAttribute(name = "Governmental")
    private int governmental;
    @XmlAttribute(name = "TaxSeason")
    private int taxSeason;
    @XmlAttribute(name = "DebentureSenderRank")
    private String debentureSenderRank;
    @XmlAttribute(name = "DebentureReceiverRank")
    private String debentureReceiverRank;
    @XmlAttribute(name = "CostCenter")
    private String costCenter;
    @XmlAttribute(name = "intAwardArticle")
    private int awardArticle;
    @XmlAttribute(name = "SecuritiesType")
    private int securitiesType;
    @XmlAttribute(name = "GuaranteeEssence")
    private int guaranteeEssence;
    @XmlAttribute(name = "Year")
    private int year;
    @XmlAttribute(name = "Nominee")
    private String nominee;
    @XmlAttribute(name = "intDemandStatus")
    private int demandStatus;
    @XmlAttribute(name = "TempPaymentType")
    private int tempPaymentType;
    @XmlAttribute(name = "LeakageSubject")
    private int leakageSubject;
    @XmlAttribute(name = "AssuranceType")
    private int assuranceType;
    @XmlAttribute(name = "AssuranceSubject")
    private int assuranceSubject;
    @XmlAttribute(name = "CurrencyType")
    private int currencyType;
    @XmlAttribute(name = "AccountNumber")
    private String accountNumber;
    @XmlAttribute(name = "InsuranceType")
    private int insuranceType;
    @XmlAttribute(name = "DebitSubject")
    private int debitSubject;
    @XmlAttribute(name = "FixedAssetType")
    private int fixedAssetType;
    @XmlAttribute(name = "InventoryType")
    private int inventoryType;
    @XmlAttribute(name = "Quantity")
    private int quantity;
    @XmlAttribute(name = "DueDate")
    private String dueDate;
    @XmlAttribute(name = "SecuritiesProperties")
    private String securitiesProperties;
    @XmlAttribute(name = "InvestmentType")
    private int investmentType;
    @XmlAttribute(name = "AnnualAdjustmentsSubject")
    private int annualAdjustmentsSubject;
    @XmlAttribute(name = "AnnualAdjustmentSubject")
    private int annualAdjustmentSubject;
    @XmlAttribute(name = "Transferitems")
    private int transferitems;
}
